In [1]:
import pandas as pd
import os

#Addig parent directory
import sys
sys.path.append('../')

In [3]:
#Importing the dataset in chunks
chunk_size = 100000
chunks = pd.read_csv('../Data/aisdk-2025-01-19.csv', chunksize=chunk_size)

chunk = next(chunks)
chunk

,# Timestamp,Type of mobile,MMSI,Latitude,Longitude,Navigational status,ROT,SOG,COG,Heading,...,Length,Type of position fixing device,Draught,Destination,ETA,Data source type,A,B,C,D
0,19/01/2025 00:00:00,Base Station,2190064,56.716553,11.519038,Unknown value,NaN,NaN,NaN,NaN,...,NaN,GPS,NaN,Unknown,NaN,AIS,NaN,NaN,NaN,NaN
1,19/01/2025 00:00:00,Class A,240716000,56.489097,11.297923,Under way using engine,0.4,13.2,53.2,52.0,...,NaN,Undefined,NaN,Unknown,NaN,AIS,NaN,NaN,NaN,NaN
2,19/01/2025 00:00:00,Class A,240716000,56.489097,11.297923,Under way using engine,0.4,13.2,53.2,52.0,...,NaN,Undefined,NaN,Unknown,NaN,AIS,NaN,NaN,NaN,NaN
3,19/01/2025 00:00:00,Class A,240716000,56.489097,11.297923,Under way using engine,0.4,13.2,53.2,52.0,...,NaN,Undefined,NaN,Unknown,NaN,AIS,NaN,NaN,NaN,NaN
4,19/01/2025 00:00:00,Class A,257079000,57.423432,6.695183,Under way using engine,0.0,3.8,98.7,94.0,...,NaN,Undefined,NaN,Unknown,NaN,AIS,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,19/01/2025 00:04:54,Class A,256959000,54.363878,10.067712,Under way using engine,0.0,4.4,231.8,233.0,...,NaN,Undefined,NaN,Unknown,NaN,AIS,NaN,NaN,NaN,NaN
99996,19/01/2025 00:04:54,Class A,256959000,54.363878,10.067712,Under way using engine,0.0,4.4,231.8,233.0,...,NaN,Undefined,NaN,Unknown,NaN,AIS,NaN,NaN,NaN,NaN
99997,19/01/2025 00:04:54,AtoN,992576506,59.018333,10.968333,Unknown value,NaN,NaN,NaN,NaN,...,NaN,Undefined,NaN,Unknown,NaN,AIS,NaN,NaN,NaN,NaN
99998,19/01/2025 00:04:54,Class A,314853000,55.457675,14.920448,Under way using engine,0.0,12.2,64.9,67.0,...,118.0,GPS,5.0,BALTIC-FOR ORDER,19/01/2025 11:00:00,AIS,96.0,22.0,14.0,5.0
99999,19/01/2025 00:04:54,AtoN,992576506,59.018333,10.968333,Unknown value,NaN,NaN,NaN,NaN,...,NaN,Undefined,NaN,Unknown,NaN,AIS,NaN,NaN,NaN,NaN

In [ ]:
#First objective is to find a specific ship and follow it through the dataset
MMSI = 240716000
chunks = pd.read_csv('../Data/aisdk-2025-01-19.csv', chunksize=chunk_size)
chunk = next(chunks)
cols = chunk.columns
print(cols)
cols_to_keep = [cols[0], cols[2], cols[3], cols[4]]

chunks = pd.read_csv('../Data/aisdk-2025-01-19.csv', chunksize=chunk_size, usecols=cols_to_keep)

ship_cols = [cols[0]] + cols_to_keep[1:] #I wanted to exclude MMSI but I failed
ship = pd.DataFrame(columns=ship_cols)

file_name = f"../Data/Single_ships/{MMSI}.csv"
if not os.path.exists(file_name):
    for i, chunk in enumerate(chunks):
        ship = pd.concat([ship, chunk[chunk['MMSI'] == MMSI][ship_cols]], ignore_index=True)
    ship.to_csv(file_name, index=False)
else:
    print(f"File {file_name} already exists!")

Index(['# Timestamp', 'Type of mobile', 'MMSI', 'Latitude', 'Longitude',
       'Navigational status', 'ROT', 'SOG', 'COG', 'Heading', 'IMO',
       'Callsign', 'Name', 'Ship type', 'Cargo type', 'Width', 'Length',
       'Type of position fixing device', 'Draught', 'Destination', 'ETA',
       'Data source type', 'A', 'B', 'C', 'D'],
      dtype='object')

C:\Users\asger\AppData\Local\Temp\ipykernel_2288\2292557094.py:17: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  ship = pd.concat([ship, chunk[chunk['MMSI'] == MMSI][ship_cols]], ignore_index=True)

In [11]:
print(i)

357